Feature/new hanged
EBombo/hanged pull request #68
Opened 2022-08-28 08:40 UTC by sebastianmendo1995

https://www.notion.so/ebombo/JUEGO-AHORCADO-99b4435b30014c65a9fcb11216a964db

2022-08-30 15:03 UTC, tech-bombo requested changes

2022-08-31 16:28 UTC, sebastianmendo1995 commented on .vscode/settings.json
> +{}
se agrego al .gitignore

2022-08-31 17:24 UTC, sebastianmendo1995 commented on functions/index.js
> +
listo

2022-09-01 14:36 UTC, tech-bombo approved these changes

2022-09-01 15:18 UTC, merged